# Generated by Django 2.2.7 on 2020-07-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200612_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.CharField(blank=True, default=1, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='productDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=30)),
                ('name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
            options={
                'verbose_name_plural': 'Details',
            },
        ),
    ]
