# Generated by Django 2.2.7 on 2020-07-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200711_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetails',
            options={'verbose_name_plural': 'Product Details'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(blank=True, default=1, null=True),
        ),
    ]
