# Generated by Django 2.2.7 on 2021-02-23 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200711_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
    ]
