# Generated by Django 2.2.7 on 2021-02-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrating',
            options={'verbose_name_plural': 'Product Rating'},
        ),
        migrations.AlterField(
            model_name='productrating',
            name='rating',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default='', max_length=1),
        ),
    ]
